### PR TITLE
Server side rendering

### PR DESCRIPTION
**Pull request by ymmn**
@ryngonzalez fully working server side rendering example with django, react, redux, and css-modules.
### Build Changes

i added another webpack entry for the server code. i thought CSS modules would be a problem, but as long as we run server and client code through the same build process, the classnames are gonna be the same. so it's all good!
### Redux + other initialization

I introduced a file for every react app called `render.js` (could use a different name?) to abstract away any initialization logic, such as making a redux store, or any initial state transformations (e.g. parsing ISO date strings into date objects). The server and the client entry point will simply call the `render` function with the initial state, and be handed back a component to directly render. Note how barebones `main/index.js` is now. There's a `apps.js` file with all the exported render functions of each app, which is what the server imports and uses.
### Front-end server Routing

Super basic. Django calls `POST localhost:3000/<app_name>` with the initial state as the JSON body.

### CODE REVIEW

**Comment by ryngonzalez** [comment]
hohohoho

**Comment by ryngonzalez** [comment]
I will look at this today

**Comment by danehansen** [comment]
any idea yet what this does to time to load the page?

**Comment by ymmn** [comment]
@danehansen the actual rendering is 1-2ms on the node server, but i should still time the overhead from the django side

**Comment by ryngonzalez** [comment]
wooo

**Comment by ryngonzalez** [comment]
merge this puppy

**Comment by ryngonzalez** [comment]
wait this was only merge 4 hours ago @ymmn? I thought this was in for a while?

**Pull request merged**
